config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'users/index'

  get 'users/show'

  resources :books do
    resources :reservations
  end

  get 'books/:id/reservations/:id/address' => 'reservations#address', as:'reservations_address'

   get '/reservations' => 'reservations#index' 
   get '/reserved' => 'reservations#reserved'
  get '/reservations' => 'reservations#show' 




  devise_for :users, :controllers => { :registrations => 'registrations' }
  resources :users, :only => [:index, :show]
  resources :users do
    member do
     get :following, :followers
    end
  end
  
  resources :relationships,       only: [:create, :destroy]







  root 'pages#index'

  get 'pages/show'

  get 'nav/rere'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
	
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reservations, dependent: :destroy
  has_many :books, dependent: :destroy
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships
     #フォローされている
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships
            
  mount_uploader :userface, ProfileUploader 
  validate  :userface_size

  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end


  def feed
    following_ids = "SELECT following_id FROM relationships
                     WHERE follower_id = :user_id"
    Book.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
  end
 
  


 

  private

  def userface_size
      if userface.size > 5.megabytes
        errors.add(:userface, "should be less than 5MB")
      end
    end     
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!


  
  def index
  	@users = User.all
  end

  def show
  	@user = User.find(params[:id])
    @books = @user.books.paginate(page: params[:page])

    @reservations = Reservation.where("user_id = ?", @user)
    
  	
  end

  def following
      @user  = User.find(params[:id])
      @users = @user.followings
      render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

  
end

app/helpers/users_helper.rb
module UsersHelper

  def current_user?(user)
     user == current_user
  end
	 
end

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build(following_id: @user.id)) do |f| %>
  <div><%= f.hidden_field :following_id %></div>
  <%= f.submit "友達になる", class: "btn btn-large btn-primary follow-btn" %></div>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>  

app/views/users/_stats.html.erb
<% @user ||= current_user %>
    <div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <div class="text-muted"><%= @user.followings.count %>   
      </strong>フォロー</div>
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
       <div class="text-muted"><%= @user.followers.count %>
    </strong>
    フォロワー</div>
  </a>
</div>
    
  

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(following_id: @user.id), html: { method: :delete }) do |f| %>
  <%= f.submit "友達解除", class: "btn btn-large follow-btn" %>
<% end %>

app/views/users/index.html.erb
<% @users.each do |user| %>
<div class="col-xs-3 col-md-2">
  

   <% if user.userface? %>
    <%= image_tag user.userface %>
    <% else %>
    <%= image_tag("userfacenoimage.png", :size => '90x90') %>

    <% end %><br>

    <div class="text-primary">
     <%= link_to user.username, user %>
     </div>


</div>
<% end %>
   

app/views/users/show.html.erb
 <body class="csstemplate">
  <div class="container">
      <div class="row">
      <div class="col-md-5  toppad  pull-right col-md-offset-3 ">
         

     
      </div>
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad" >
   
   
          <div class="panel panel-info">
            <div class="panel-heading">
              <h3 class="panel-title">プロフィール</h3>
            </div>
            <div class="panel-body">
              <div class="row">
                <div class="col-md-3 col-lg-3 " align="center" class="img-thumbnail">
                 <% if @user.userface? %> 
                   <%= image_tag @user.userface %>
                   <% else %>
                    <%= image_tag("userfacenoimage.png", :size => "90x90") %>
                    
                 <% end %>
                 <%= render 'follow_form' %>
                 <section class="stats">
                <%= render 'stats' %>
                </section>

                
                

                 </div>
                
           
                <div class=" col-md-9 col-lg-9 "> 
                  <table  class="table table-striped">
                    <tbody>
                      <tr>
                        <td>名前</td>
                        <td><%= @user.username %></td>
                      </tr>
                      <tr>
                        <td>現在の仕事</td>
                        <td><%= @user.work %></td>
                      </tr>
                      <tr>
                        <td>普段の生活</td>
                        <td><div class="form-group"><%= @user.life %></div></td>
                      </tr>
                   
                      <tr>
                            
                        <td>好きな本</td>
                        <td><%= @user.likebook %></td>
                      </tr>
                        <tr>
                        <td>好きな本の理由</td>
                        <td><div class="form-group"><%= @user.likebookwhy %></div></td>
                      </tr>
                      <tr>
                        <td>読書生活</td>
                        <td><div class="form-group"><%= @user.booklife %></td>　
                      </tr>　
                        　
                           
                      </tr>
                     
                    </tbody>
                  </table>
                
                </div>
              </div>
            </div>
                 
          </div>
        </div>
      </div>
    </div>
  
 <%= render @books %>


 </body>

app/views/users/show_follow.html.erb
<% @user.followings.each do |user| %>
<table>
<tr>
  <td>  <%= user.username %> </td>
  <td><%= link_to '詳細', user_path(user) %></td>
</tr>

</table>
<% end %>

app/views/users/show_follower.html.erb
<% @user.followers.each do |user| %>
<div class="col-xs-3 col-md-2">
  

   <% if user.userface? %>
    <%= image_tag user.userface %>
    <% else %>
    <%= image_tag("userfacenoimage.png", :size => '90x90') %>

    <% end %><br>

   
     <button class="btn btn-info"><%= link_to user.username, user, :style=>"color:white;"  %></button>
</div>
<% end %>