config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'users/index'

  get 'users/show'

  resources :books do
    resources :reservations
  end

  get 'books/:id/reservations/:id/address' => 'reservations#address', as:'reservations_address'

   get '/reservations' => 'reservations#index' 
   get '/reserved' => 'reservations#reserved'
  get '/reservations' => 'reservations#show' 




  devise_for :users, :controllers => { :registrations => 'registrations' }
  resources :users, :only => [:index, :show]
  resources :users do
    member do
     get :following, :followers
    end
  end
  
  resources :relationships,       only: [:create, :destroy]







  root 'pages#index'

  get 'pages/show'

  get 'nav/rere'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :user
  has_many :reservations
  default_scope -> { order(created_at: :desc) }
  
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validate  :picture_size

   def self.from_users_followed_by(user)
    following_ids = user.following_ids
    where("user_id IN (?) OR user_id = ?", following_ids, user)
  end

  private

  #アップロードされた画像のサイズをバリデーションする
  def picture_size
  if picture.size > 5.megabytes
    errors.add(:picture, "should be less than 5MB")
   end
  end  	

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  before_action :set_book, only: [:show, :edit, :update, :destroy]


  def index
    @books = current_user.books.all
    @books = Book.paginate(:page => params[:page], :per_page => 12)
    @reservations = Reservation.all

  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = current_user.books.build
  end

  def create
    @book = current_user.books.build(book_params)

    if @book.save
      redirect_to root_path, notice:"保存しました"
    else
       redirect_to new_book_path(@book), notice:"保存してない"
    end 

    
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book.update(book_params)
    respond_with(@book)
    flash[:success] = "book update"
    
  end

  def destroy
    @book.destroy
       flash[:success] = "book deleted"
       redirect_to request.referrer || root_url
  end

 

  private

   def book_params
     params.require(:book).permit(:title, :author, :publish, :sort, :like, :impressions, :picture)
   end

   def set_book
    @book = Book.find(params[:id])
   end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
  <div class="container">
  <div class="row"> 
    <div class="col-xs-6 col-md-3">
        <td><%= image_tag book.picture.url if book.picture? %></td>
           <h3><%= book.title %></h3>
           <p><%= book.author %></p>
           <p><%= book.publish %></p>
           <p><%= book.sort %></p>
           <p><%= book.like %></p>
           

                     <div class="btn-group">
              <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                感想を見る
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu" role="menu">
                <li role="presentation"><a role="menuitem" tabindex="-1" href="#"><p><%= book.impressions %></p> </a></li>
                </ul>
              </div>
          <%= link_to "", book, method: :delete, data: { confirm: "本当に削除しますか？" }, :class => "btn btn-sm btn-danger glyphicon glyphicon-trash" %>

          <%= link_to "本の詳細", book_path(book) %>


                              
          


    
                
          </div>
     
    　</div>
           
  </div>
</div>

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/edit.html.erb
<%= form_for (@book) do |f| %>

     <div class="text-center">
      <span style="font-size:24px;">本の情報編集</span>
     </div>
   <div class="row">
    
    <div class="container">
		<div class="form-group">
		 <label>本のタイトル</label>
		 <%= f.text_field :title, :class => 'form-control' %>
		</div> 
      
		<div class="form-group">
		 <label>本の著者</label>
		 <%= f.text_field :author, :class => 'form-control' %>
		</div> 

		<div class="form-group">
		 <label>本の出版社</label>
		 <%= f.text_field :publish, :class => 'form-control' %>
		</div> 

		<div class="form-group">
		 <label>本の分類</label>
		 <%= f.select :sort,options_for_select([["哲学", "哲学"], ["歴史", "歴史"], ["社会", "社会"],["自然", "自然"],["技術", "技術"],["産業", "産業"],["芸術", "芸術"],["言語", "言語"],["文学", "文学"]]), {},:class => 'form-control' %>
		</div> 

		 <div class="form-group">
		  <label>オススメ度</label>
		 <%= f.select :like, options_for_select([["おすすめしない(★)", "★"], ["あまりおすすめしない(★★)", "★★"], ["ふつう(★★★)", "★★★"],["おすすめ(★★★)", "★★★★"],["とてもおすすめ(★★★★★)", "★★★★★"]]), {},:class => 'form-control' %>
		 </div>

		 <label>画像</label>
		 <div class="input-group">

			  <span class="input-group-btn">
			    <span class="btn btn-small btn-primary btn-inverse" onclick="$(this).parent().find('input[type=file]').click();"><div class='glyphicon glyphicon-file'></div></span>
			    <%= f.file_field :picture, onchange: "$(this).parent().parent().find('.form-control').html($(this).val().split(/[\\\\|/]/).pop());", accept: 'image/jpeg,image/gif,image/png',style: "display: none;" %>
			  </span>
			  <span class="form-control"></span>
	     </div>


		 
		<div class="form-group">
		 <label>感想</label>
		  <%= f.text_area :impressions, :class => 'form-control' %>
		</div> 

        <div class="text-center">
		<%= f.submit "本の情報を編集する", class: "text-center", class: "btn btn-success" %>
		</div>

		
       
		<% end %>

		<script type="text/javascript">
			  $('#micropost_picture').bind('change', function() {
			    var size_in_megabytes = this.files[0].size/1024/1024;
			    if (size_in_megabytes > 5) {
			      alert('Maximum file size is 5MB. Please choose a smaller file.');
			    }
			  });
　　　　</script>


	</div>	
　　
  </div>

app/views/books/index.html.erb
<div id="bookheader" class="text-right">
     <%= will_paginate @books, :renderer => BootstrapPagination::Rails %>
 </div>    

<div class="container">
  <div class="row">
    <% @books.each do |book| %>

    <div class="col-xs-6 col-md-3">
        <td><%= image_tag book.picture.url if book.picture? %></td>
           <h3><%= book.title %></h3>
           <p><%= book.author %></p>
           <p><%= book.publish %></p>
           <p><%= book.sort %></p>
           <p><%= book.like %></p>
           

                     <div class="btn-group">
              <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                感想を見る
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu" role="menu">
                <li role="presentation"><a role="menuitem" tabindex="-1" href="#"><p><%= book.impressions %></p> </a></li>
                </ul>
              </div>
          <%= link_to "", book, method: :delete, data: { confirm: "本当に削除しますか？" }, :class => "btn btn-sm btn-danger glyphicon glyphicon-trash" %> 

    



    
                
          </div>
     <% end %>
     
    　</div>
           
  </div>
</div>

<h2>自分が借りるリスト</h2>
 <table>

    <% @reservations.each do |reservation| %>
     
        <%= reservation.start_date.strftime('%Y年%m月%d日') %>
        <%= reservation.end_date.strftime('%Y年%m月%d日') %>
 

    <% end %>
   </table> 

app/views/books/new.html.erb
<%= form_for (@book) do |f| %>

     <div class="text-center">
      <span style="font-size:24px;">本の登録</span>
     </div>
   <div class="row">
    
    <div class="container">
		<div class="form-group">
		 <label>本のタイトル</label>
		 <%= f.text_field :title, :class => 'form-control' %>
		</div> 
      
		<div class="form-group">
		 <label>本の著者</label>
		 <%= f.text_field :author, :class => 'form-control' %>
		</div> 

		<div class="form-group">
		 <label>本の出版社</label>
		 <%= f.text_field :publish, :class => 'form-control' %>
		</div> 

		<div class="form-group">
		 <label>本の分類</label>
		 <%= f.select :sort,options_for_select([["哲学", "哲学"], ["歴史", "歴史"], ["社会", "社会"],["自然", "自然"],["技術", "技術"],["産業", "産業"],["芸術", "芸術"],["言語", "言語"],["文学", "文学"]]), {},:class => 'form-control' %>
		</div> 

		 <div class="form-group">
		  <label>オススメ度</label>
		 <%= f.select :like, options_for_select([["おすすめしない(★)", "★"], ["あまりおすすめしない(★★)", "★★"], ["ふつう(★★★)", "★★★"],["おすすめ(★★★)", "★★★★"],["とてもおすすめ(★★★★★)", "★★★★★"]]), {},:class => 'form-control' %>
		 </div>

		 <label>画像</label>
		 <div class="input-group">

			  <span class="input-group-btn">
			    <span class="btn btn-small btn-primary btn-inverse" onclick="$(this).parent().find('input[type=file]').click();"><div class='glyphicon glyphicon-file'></div></span>
			    <%= f.file_field :picture, onchange: "$(this).parent().parent().find('.form-control').html($(this).val().split(/[\\\\|/]/).pop());", accept: 'image/jpeg,image/gif,image/png',style: "display: none;"  %>
			  </span>
			  <span class="form-control"></span>
	     </div>


		 
		<div class="form-group">
		 <label>感想</label>
		  <%= f.text_area :impressions, :class => 'form-control' %>
		</div> 

        <div class="text-center">
		<%= f.submit "本を登録する", class: "text-center", class: "btn btn-success" %>
		</div>

		
       
		<% end %>

		<script type="text/javascript">
			  $('#micropost_picture').bind('change', function() {
			    var size_in_megabytes = this.files[0].size/1024/1024;
			    if (size_in_megabytes > 5) {
			      alert('Maximum file size is 5MB. Please choose a smaller file.');
			    }
			  });
　　　　</script>


	</div>	
　　
  </div>

app/views/books/show.html.erb
<div class="container">
 <div class="row">
  <div class="col-xs-6">
   <%= image_tag @book.picture  %>
        

        <table class="table table-striped">
          <thead>
            <tr>
              <th>本のタイトル</th>
              <th> <%= @book.title %></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th scope="row">本の著者</th>
              <td><%= @book.author %></td>
              
            </tr>
            <tr>
              <th scope="row">出版社</th>
              <td><%= @book.publish %></td>
              
            </tr>
            <tr>
              <th scope="row">本の種類</th>
              <td><%= @book.sort %></td>
              
            </tr>
            <tr>
              <th scope="row">本の種類</th>
              <td><%= @book.like %></td>
              
            </tr>
          </tbody>
        </table>

   </div>

     <div class="col-xs-6">
          <div class="panel panel-info">
            <div class="panel-heading">
              <h3 class="panel-title">感想</h3>
            </div>
            　<div class="panel-body">
              　<%= @book.impressions %>
            　</div>
          </div>
     </div>  
  </div>
 </div>    
  

  <%=  @book.user_id %>
  <%= current_user.id %>

<% if @book.user_id == current_user.id  %>

<% else %>
 <%= form_for ([@book, @book.reservations.build]) do |f| %>

 <%= f.hidden_field :book_id, value: @book.id %>
 <%= f.hidden_field :consent, :value => "承認中" %>
 
 
   <div class="container">
    <div class="row">
        <div class='col-sm-6'>
 
       <div class="form-group">
       <div class='input-group date' id='datetimepicker6'>
      <%= f.text_field :start_date, :class => 'datepicker form-control' %>
       <span class="input-group-addon">
            <span class="glyphicon glyphicon-calendar"></span>
       </span>
       </div>
        </div>
        </div>
        </div>
        </div>


         <div class="container">
    <div class="row">
        <div class='col-sm-6'>
 
       <div class="form-group">
       <div class='input-group date' id='datetimepicker7'>
<%= f.text_field :end_date, :class => 'datepicker form-control' %>
       <span class="input-group-addon">
            <span class="glyphicon glyphicon-calendar"></span>
       </span>
       </div>
        </div>
        </div>
        </div>
        </div>






   <%= f.submit "この日程で予約する", class: "btn btn-danger btn-wide" %>    


<% end %>

<% end %>


<script type="text/javascript">
var data = {'data-date-format': 'YYYY-MM-DD' };

var ready = function(){
  $('.datepicker').attr(data);
  $('.datepicker').datetimepicker();
};

$(document).ready(ready);
$(document).on('page:load', ready);



</script>


<script type="text/javascript">
    $(function () {
        $('#datetimepicker6').datetimepicker();
        $('#datetimepicker7').datetimepicker({
            useCurrent: false //Important! See issue #1075
        });
        $("#datetimepicker6").on("dp.change", function (e) {
            $('#datetimepicker7').data("DateTimePicker").minDate(e.date);
        });
        $("#datetimepicker7").on("dp.change", function (e) {
            $('#datetimepicker6').data("DateTimePicker").maxDate(e.date);
        });


    });

</script>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>