config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'users/index'

  get 'users/show'

  resources :books do
    resources :reservations
  end

  get 'books/:id/reservations/:id/address' => 'reservations#address', as:'reservations_address'

   get '/reservations' => 'reservations#index' 
   get '/reserved' => 'reservations#reserved'
  get '/reservations' => 'reservations#show' 




  devise_for :users, :controllers => { :registrations => 'registrations' }
  resources :users, :only => [:index, :show]
  resources :users do
    member do
     get :following, :followers
    end
  end
  
  resources :relationships,       only: [:create, :destroy]







  root 'pages#index'

  get 'pages/show'

  get 'nav/rere'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
class Reservation < ApplicationRecord

  belongs_to :user
  belongs_to :book

  geocoded_by :address
after_validation :geocode, if: :address_changed?
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

   def index
       @reservations = current_user.reservations.all
   end

   

   def create
     @reservation = current_user.reservations.create(reservation_params)
     
     redirect_to pages_show_path, notice: "予約完了しました"

   end

   def destroy

   end

   def show
      @reservation = Reservation.find(params[:id])
   end 

   def edit
    @reservation = Reservation.find(params[:id])

   end 

   def update
     @reservation = Reservation.find(params[:id])

     if @reservation.update(reservation_params)
      redirect_to :back, notice: "更新できました"
     end
      
    end

  

   def reserved
     @books = current_user.books
    
   end

    def address
     @reservation = Reservation.find(params[:id])
     if @reservation.update(reservation_params)
      redirect_to :back, notice: "更新できました"
     end
      
   end 
    

   
    

  private

  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date, :book_id, :consent, :address)
  end 

end    

app/helpers/reservation_helper.rb
module ReservationHelper
end

app/views/reservations/address.html.erb
<%= form_for @reservation,  :url => {:action => :update} do |f| %>

 <%= f.text_field :address %>

    <%= f.submit "いいよ!", class: "btn btn-primary center-block" %>

 
 <% end %>re

app/views/reservations/edit.html.erb
<%= form_for @reservation, :url => {:action => :update}   do |f| %>

 <div class="text-center"><%= f.text_field :address %></div>

    <%= f.submit "待ち合わせ登録", class: "btn btn-primary center-block" %>

 
 <% end %>


 <body>
    <div id="map"></div>
    <style>
    	#map {
        height: 500px;
        width: 70%;
      }
    </style>
    <script>
      function initMap() {
        var uluru = {lat: <%= @reservation.latitude %>, lng: <%= @reservation.longitude %>};
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 16,
          center: uluru
        });
        var marker = new google.maps.Marker({
          position: uluru,
          map: map
        });
      }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB34ifLuCQWsdOXVdW97YwamxcI5Svwh-s&callback=initMap"
    async defer></script>
  </body>

app/views/reservations/index.html.erb
 <table>
 <% @reservations.each do |reservation| %>

 <%= reservation.consent %>
 <%= reservation.book.user.username%>
 <%= reservation.book.title%>
 
 <%= reservation.start_date.strftime('%Y年%m月%d日') %>
 <%= reservation.end_date.strftime('%Y年%m月%d日') %>

 

 <% end %>
 </table>

app/views/reservations/reserved.html.erb
 
<table class="table">

<tr>
 <th>承認ボタン</th>
 <th>承認状況</th>
 <th>本の名前</th>
 <th>名前</th>
 <th>貸出日</th>
 <th>返却日</th>
	


</tr>
<tr>
 <% @books.each do |book| %>
 <% book.reservations.each do |reservation| %>

      <td><%= link_to "承認ボタン",book_reservation_path(book,reservation),  :class => 'btn btn-mini btn-danger' %></td>
       <td><%= reservation.consent %></td>
      <td><%= book.title %></td>
      <td><%= reservation.user.username %></td>
      <td><%= reservation.start_date.strftime('%Y年%m月%d日') %></td>
       <td><%= reservation.end_date.strftime('%Y年%m月%d日') %></td>
</tr>       

<% end %>
<% end %>

</table>

app/views/reservations/show.html.erb
 <div id="reservationpadding">
 <div class="row">
 

         <div class="col-sm-4 col-sm-offset-1">
         <% if @reservation.book.picture? %>
                <%= image_tag @reservation.book.picture  %>
                <% else %>
                <%= image_tag("book.image.png", :size => '300x300') %>

                <% end %>
            


         </div>

              <div class="col-sm-6">   

                  <table class="table table-striped table-bordered">
                   <thead>
                      <tr>
                        <th>借りたい人の名前</th>
                        <th><%= @reservation.user.username %></th>
                      </tr>
                    </thead>
                     <tbody>
                       <tr>
                        <th>本のタイトル</th>
                        <th> <%= @reservation.book.title %></th>
                      </tr>
                    
                      <tr>
                        <th>借りたい日</th>
                        <th><%= @reservation.start_date.strftime('%Y年%m月%d日') %></th>　
                      </tr>
                       <tr>
                        <th>返す日</th>
                        <th><%= @reservation.end_date.strftime('%Y年%m月%d日') %></th>　
                      </tr>
                    
                    
                      <tr>
                        <th>本のタイトル</th>
                        <th> <%= @reservation.book.title %></th>
                      </tr>
                    
                   
                      <tr>
                        <th scope="row">本の著者</th>
                        <td><%= @reservation.book.author %></td>
                        
                      </tr>
                      <tr>
                        <th scope="row">出版社</th>
                        <td><%= @reservation.book.publish %></td>
                        
                      </tr>
                    </tbody>
                  </table>
          </div>
 </div>
 </div>  

 </div><br>

<div  class="text-center"> 
  <label>上の内容でよろしいですか？</label>


</div>
 <!-- 同意ボタン-->
 <%= form_for @reservation, :url => {:action => :update} do |f| %>
    <%= f.hidden_field :consent, :value => "いいよ!" %>

    <%= f.submit "いいよ!", class: "btn btn-primary center-block" %>

 
 <% end %>
 <!-- 修正ボタン-->
 <%= form_for @reservation, :url => {:action => :update} do |f| %>
    <%= f.hidden_field :consent, :value => "だめよ!" %>

 <div id="damedame">
 <%= f.submit "だめ", class: "btn btn-danger center-block "  %>
 </div>
 <% end %>

 <%= form_for @reservation, :url => {:action => :update} do |f| %>

 <%= f.text_field :address %>

    <%= f.submit "住所!", class: "btn btn-primary center-block" %>

 
 <% end %>

 <div class="col-md-8 col-md-offset-2" >
       <div id="dateupdate">
       <%= form_for @reservation, :url => {:action => :update} do |f| %>

         <label>借りる日</label>
          <%= f.date_field :start_date %>

           <label>借りる日</label>
      <%= f.date_field :end_date %>
       
       <%= f.submit "日付更新", class: "btn btn-success btn-wide" %>
       <% end %>

       </div> 
 </div> 
   
         
       



  