config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'users/index'

  get 'users/show'

  resources :books do
    resources :reservations
  end

  get 'books/:id/reservations/:id/address' => 'reservations#address', as:'reservations_address'

   get '/reservations' => 'reservations#index' 
   get '/reserved' => 'reservations#reserved'
  get '/reservations' => 'reservations#show' 




  devise_for :users, :controllers => { :registrations => 'registrations' }
  resources :users, :only => [:index, :show]
  resources :users do
    member do
     get :following, :followers
    end
  end
  
  resources :relationships,       only: [:create, :destroy]







  root 'pages#index'

  get 'pages/show'

  get 'nav/rere'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
     if user && user.admin_flg?
      can :access, :rails_admin
      can :manage, :all
    end
    
  end
end

# Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :user
  has_many :reservations
  default_scope -> { order(created_at: :desc) }
  
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validate  :picture_size

   def self.from_users_followed_by(user)
    following_ids = user.following_ids
    where("user_id IN (?) OR user_id = ?", following_ids, user)
  end

  private

  #アップロードされた画像のサイズをバリデーションする
  def picture_size
  if picture.size > 5.megabytes
    errors.add(:picture, "should be less than 5MB")
   end
  end  	

end

app/models/lend.rb
class Lend < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord

    belongs_to :follower, class_name: "User"
    belongs_to :following, class_name: "User"
    validates :follower_id, presence: true
    validates :following_id, presence: true

end

app/models/reservation.rb
class Reservation < ApplicationRecord

  belongs_to :user
  belongs_to :book

  geocoded_by :address
after_validation :geocode, if: :address_changed?
end

app/models/user.rb
class User < ApplicationRecord
	
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reservations, dependent: :destroy
  has_many :books, dependent: :destroy
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships
     #フォローされている
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships
            
  mount_uploader :userface, ProfileUploader 
  validate  :userface_size

  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end


  def feed
    following_ids = "SELECT following_id FROM relationships
                     WHERE follower_id = :user_id"
    Book.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
  end
 
  


 

  private

  def userface_size
      if userface.size > 5.megabytes
        errors.add(:userface, "should be less than 5MB")
      end
    end     
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
        pages_show_path
    end

    private
        def sign_in_required
            redirect_to new_user_session_url unless user_signed_in?
        end

     protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
      devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email, :userface, :work, :life, :likebook, :likebookwhy, :booklife])
    end    
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  before_action :set_book, only: [:show, :edit, :update, :destroy]


  def index
    @books = current_user.books.all
    @books = Book.paginate(:page => params[:page], :per_page => 12)
    @reservations = Reservation.all

  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = current_user.books.build
  end

  def create
    @book = current_user.books.build(book_params)

    if @book.save
      redirect_to root_path, notice:"保存しました"
    else
       redirect_to new_book_path(@book), notice:"保存してない"
    end 

    
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book.update(book_params)
    respond_with(@book)
    flash[:success] = "book update"
    
  end

  def destroy
    @book.destroy
       flash[:success] = "book deleted"
       redirect_to request.referrer || root_url
  end

 

  private

   def book_params
     params.require(:book).permit(:title, :author, :publish, :sort, :like, :impressions, :picture)
   end

   def set_book
    @book = Book.find(params[:id])
   end

end

app/controllers/lends_controller.rb
class LendsController < ApplicationController

   def index
       @lends = current_user.lends
   end
    

   def create
     @lend = current_user.lends.create(lend_params)

     redirect_to pages_show_path, notice: "予約完了しました"

   end

   def destroy
     @lend = Lends.find(params[:id])
   end
    
    

  private

  def lend_params
    params.require(:lend).permit(:start, :end, :book_id)
  end 

end    

app/controllers/nav_controller.rb
class NavController < ApplicationController
  def rere
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	 before_action :sign_in_required, only: [:show]
  def index
  end

  def show
  	  @feed_items = current_user.feed.paginate(page: params[:page])
  	  
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!


  
  def index
  	@users = User.all
  end

  def show
  	@user = User.find(params[:id])
    @books = @user.books.paginate(page: params[:page])

    @reservations = Reservation.where("user_id = ?", @user)
    
  	
  end

  def following
      @user  = User.find(params[:id])
      @users = @user.followings
      render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/nav_helper.rb
module NavHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/reservation_helper.rb
module ReservationHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def current_user?(user)
     user == current_user
  end
	 
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>DeviseRails5</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>

     <header class="navbar-fixed-top">
          <nav class="navbar navbar-default">
                  <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#gnavi">
                        <span class="sr-only">メニュー</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                  </div>
                  
                  <% if user_signed_in? %>

                  <div id="gnavi" class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                      <li><%= link_to current_user.username, pages_show_path %></li>
                      <li><%= link_to 'プロフィール変更', edit_user_registration_path %></li>
                      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
                      <li class="dropdown dropdown-submenu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">詳細</a>
                            <ul class="dropdown-menu">
                               <li><li><%= link_to '本の登録', new_book_path %></li></li>
                               <li><li><%= link_to 'プロフィール', user_path(current_user) %></li></li>
                               <li><li><%= link_to '借りたい', reservations_path  %></li></li>
                               <li><li><%= link_to '貸す', reserved_path %></li></li>
                               <li><li><%= link_to 'ユーザー一覧', users_path%></li></li>
                            </ul>
                          </li>

                    </ul>  
                   </div>

                 <% else %>

                 <div id="gnavi" class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                      <li></li>
                      <li><%= link_to 'このサイトの説明'%></li>
                      <li><%= link_to 'ログイン', new_user_session_path %></li>
                      <button type="button" class="btn btn-default navbar-btn"><%= link_to 'サインアップ', new_user_registration_path %></button>
                      </li>
                          
                  <% end %> 

          </nav>
           
      </header>
 
        


        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>

        <!-- flashにメッセージがある時 -->
            <% unless flash.empty? %>
             　<script type="text/javascript">
             　　<% flash.each do |f| %>
             　　　<% type = f[0].to_s.gsub('alert','error').gsub('notice','info') %>
            　　　　　toastr['<%= type %>']('<%=f[1] %>');
             　　<% end %>
            　　</script>
            <% end %>


        


        <%= yield %>
    </body>
</html>

app/views/pages/index.html.erb
<header class="business-header">
        <div class="container">
            <div class="row">
                <div class="col-lg-12  text-center">
                    <br><br><br><br><br><br>
                    <hr>
                    <h1 class="tagline" id="h1">みんなの図書館</h1>
                    <hr>
                    <p id="h1under">本の評価をみんな作ろう </p>
                    <p id="h1under">本をシェアしよう</p>
                    <br>
                    <a><%= link_to 'サインアップ', new_user_registration_path, :class => 'btn btn-primary active'  %></a> 
                </div>
            </div>
        </div>
    </header>

<div class="container">

<div class="row">
    <div class="col-xs-6 col-md-3">
        <%= image_tag("money.png", :size => "210x210", :alt => "アイコン", :class => 'thumbnail', :class => 'img-circle') %>
        <div class="well" id="money">いらなくなった本などを、フリーマーケットに出すことができます。</div>
    </div>
    <div class="col-xs-6 col-md-3">
        <%= image_tag("dokusyo.png", :size => "210x210", :alt => "アイコン", :class => 'thumbnail', :class => 'img-circle') %>
        <div class="well" id="dokusyo">読書の習慣を身につけよう。</div>
    </div>
    <div class="col-xs-6 col-md-3">
        <%= image_tag("it.png", :size => "210x210", :alt => "アイコン", :class => 'thumbnail', :class => 'img-circle') %>
         <div class="well" id="it">ITを作って効率的に読書をしよう</div>　
    </div>
    <div class="col-xs-6 col-md-3">
        <%= image_tag("view.png", :size => "210x210", :alt => "アイコン", :class => 'thumbnail', :class => 'img-circle') %>
　　　　　<div class="well" id="view">読んだ本の評価をみんなに発信しよう!</div>
    </div>
</div>
</div>

app/views/pages/show.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/partial/_deviseErrorMsg.html.erb
<% unless resource.errors.empty? %>
　<script type= "text/javascript">
　　<% resource.errors.full_messages.each do |msg| %>
　　　toastr.error('<%= msg %>');
　　<% end %>
　</script>
<% end %>